Traceback (most recent call last):
  File "calib_flux.py", line 161, in <module>
    id_num = str(sys.argv([1]))
TypeError: 'list' object is not callable
